In [1]:
import pandas as pd

df = pd.read_csv('train_onehot.csv')

In [5]:
df_ = df.fillna(df.median())

In [6]:
df_

,continuous_f0024,continuous_f0080,continuous_f0087,continuous_f0101,continuous_f0122,continuous_f0248,continuous_f0262,continuous_f0269,continuous_f0304,continuous_f0346,...,discrete_f0001_11_one_hot,discrete_f0001_12_one_hot,discrete_f0001_13_one_hot,discrete_f0001_14_one_hot,discrete_f0001_15_one_hot,discrete_f0001_16_one_hot,discrete_f0001_17_one_hot,discrete_f0001_18_one_hot,discrete_f0001_19_one_hot,discrete_f0177_1_one_hot
0,10.0,1.0,0.002000,0.824859,0,2.424658,0,3,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
1,10.0,1.0,0.001000,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
2,10.0,1.0,0.010000,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
3,10.0,1.0,0.002000,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
4,10.0,1.0,0.002000,0.448679,0,3.745205,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,10.0,1.0,0.002000,0.140196,0,14.265753,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
99996,10.0,1.0,0.002000,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
99997,10.0,1.0,0.020000,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
99998,10.0,1.0,0.002000,0.060241,0,16.600000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
99999,10.0,1.0,0.000199,0.221901,0,0.000000,0,0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1